[tools]
bun = "latest"
deno = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
node = "latest"
pipx = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
